version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip3 install pytest
  build:
    commands:
      - python3 -m venv test_venv
      - . test_venv/bin/activate
      - pip install --upgrade pip
      - pip3 install -r requirements.txt
      - python3 -m pytest tests/ --junitxml=pytest_reports/pytest_report.xml
      - export BUCKET=danielArtifactsBucket
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml

artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml